# =====================================================
# CONFIGURACIÓN DEL PROYECTO - PC1
# =====================================================
audio=../input/audio/audio_base.wav
imagesFolder=../input/images

fps=12

# Modos: serial | parallel | both
mode=both

# Cantidad de hilos para procesamiento paralelo
threads=4

serialOutput=output/frames_serial
parallelOutput=output/frames_parallel

# Archivos de salida MP4
videoSerial=videoclip_serial.mp4
videoParallel=videoclip_parallel.mp4
